### ISSUE TITLE
Add optional support for webhooks

### ISSUE THREAD

**Issue by ririko5834** [eartharoid/leekslazylogger#15]
Add option that you can set webhook url to every log level, and when something is logged make POST request with body in json format `{"log": "log will be here"}` to the webhook url.

This will be good if you have more project workers and want to have one log from all of them. 
Then you can handle the webhook post requests as you want.

**Comment by eartharoid** [comment]
This is now possible with https://logger.eartharoid.me/transports/creating-a-transport/

**Comment by ririko5834** [comment]
Is there example code?

**Comment by eartharoid** [comment]
```js
const Transport = require('leekslazylogger/dist/transport');
const fetch = require('node-fetch');
class HTTPTransport extends Transport {
	constructor(level) {
		super({ level: level || 'info' });
	}

	write(log) {
		// log = https://github.com/eartharoid/leekslazylogger/blob/912d0b520b8234b61a1a4739a2c354a6b6c8a290/src/types.ts#L29
		fetch('http://example.com', {
			method: 'post',
			body: JSON.stringify(log),
			headers: { 'Content-Type': 'application/json' }
		});

	}
}

const log = new Logger({
	transports: [
		new HTTPTransport('info')
	]
});
```
